create_product:
  path: /api/product/create
  controller: App\Controller\ApiProductController::createProduct
  methods: POST
  condition:  "request.headers.get('Content-Type') matches '/application\\\\/json/'"

product_list:
  path: /api/product/list
  controller: App\Controller\ApiProductController::getList
  methods: GET

products_in_category:
  path: /api/category/products/{id}
  controller: App\Controller\ApiCategoryController::getProductsInCategory
  methods: GET
  format: json
  requirements:
    id: '\d+'
    _format: json
  defaults:
    id: 1

get_product_by_id:
  path: /api/product/{id}
  controller: App\Controller\ApiProductController::getById
  methods: GET
  format: json
  requirements:
    id: '\d+'
    _format: json

create_category:
  path: /api/category/create
  controller: App\Controller\ApiCategoryController::createCategory
  methods: POST
  condition:  "request.headers.get('Content-Type') matches '/application\\\\/json/'"